packages:
  - frontend
  - ai
  - contracts
  - shared
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tarojs/binding'
  - '@tarojs/cli'
  - core-js
  - core-js-pure
  - esbuild
  - keccak
